# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnest.proto\x12\x1d\x63om.naver.clova.speech.client\"p\n\x0bNestRequest\x12;\n\x06\x63onfig\x18\x01 \x01(\x0b\x32).com.naver.clova.speech.client.NestConfigH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\x13\n\x11streaming_request\"\x1c\n\nNestConfig\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\t\" \n\x0cNestResponse\x12\x10\n\x08\x63ontents\x18\x01 \x01(\t2w\n\x0bNestService\x12h\n\trecognize\x12*.com.naver.clova.speech.client.NestRequest\x1a+.com.naver.clova.speech.client.NestResponse(\x01\x30\x01\x42,\n\x1d\x63om.naver.clova.speech.clientB\tNestProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.naver.clova.speech.clientB\tNestProtoP\001'
  _globals['_NESTREQUEST']._serialized_start=45
  _globals['_NESTREQUEST']._serialized_end=157
  _globals['_NESTCONFIG']._serialized_start=159
  _globals['_NESTCONFIG']._serialized_end=187
  _globals['_NESTRESPONSE']._serialized_start=189
  _globals['_NESTRESPONSE']._serialized_end=221
  _globals['_NESTSERVICE']._serialized_start=223
  _globals['_NESTSERVICE']._serialized_end=342
# @@protoc_insertion_point(module_scope)
