export const medicalKeywords = [
    { words: "추나", boost: 2.0 },
    { words: "추나치료", boost: 2.0 },
    { words: "약침", boost: 2.0 },
    { words: "봉침", boost: 2.0 },
    { words: "어혈", boost: 1.5 },
    { words: "공진단", boost: 2.0 },
    { words: "경옥고", boost: 2.0 },
    { words: "발침", boost: 1.5 },
    { words: "유침", boost: 1.5 },
    { words: "전침", boost: 1.5 },
    { words: "부항", boost: 1.5 },
    { words: "사혈", boost: 1.5 },
    { words: "맥진", boost: 1.5 },
    { words: "복진", boost: 1.5 },
    { words: "설진", boost: 1.5 },
    { words: "탕전", boost: 1.5 },
    { words: "첩약", boost: 1.5 },
    { words: "초진", boost: 1.2 },
    { words: "재진", boost: 1.2 },
    { words: "예진", boost: 1.2 },
    { words: "원장님", boost: 1.2 },
    { words: "간호사님", boost: 1.2 },
    { words: "실장님", boost: 1.2 },
    { words: "데스크", boost: 1.2 },
    { words: "치료실", boost: 1.2 },
    { words: "수납", boost: 1.2 },
    { words: "예약", boost: 1.2 },
    // 혈자리 (예시)
    { words: "합곡", boost: 2.0 },
    { words: "태충", boost: 2.0 },
    { words: "족삼리", boost: 2.0 },
    { words: "곡지", boost: 2.0 }
];
